base_url = "https://marcoabbadini.github.io"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

theme = "anemone"

default_language = "en"
title = "Marco Abbadini"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "off"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Marco Abbadini"
image = ""
list_pages = false
twitter_card = false
favicon = "favicon.png"
enable_search = true

header_nav = [
	{ name_en = "/home", url = "/" },
	{ name_en= "/about", url = "/about" },
	{ name_en  = "/teaching", url = "/teaching" },
	{ name_en = "/publications", url = "/publications" },
	{ name_en = "/posts", url = "/posts" },
	{ name_en = "/contacts", url = "/contacts" },
	{ name_en = "/UNIBG", url = "https://cs.unibg.it/abbadini"},
	{ name_en = "/IMDEA", url = "https://software.imdea.org/people/marco.abbadini/"}
]
